language: java

os:
  - linux

jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
    - name: Linux / FusionDB Server Nightly
      os: linux
      env:
        - DOCKER_DB_IMAGE=repo.evolvedbinary.com:9543/evolvedbinary/fusiondb-server:nightly
      script: mvn verify -Ddocker.username=$FDB_NIGHTLY_DOCKER_USER -Ddocker.password=$FDB_NIGHTLY_DOCKER_PASS -Dapi.port=4059 -Ddocker.db.image=$DOCKER_DB_IMAGE -B

    - name: Linux / FusionDB Server 1.0.0-ALPHA3
      os: linux
      env:
        - DOCKER_DB_IMAGE=repo.evolvedbinary.com:9443/evolvedbinary/fusiondb-server:1.0.0-ALPHA3
      script: mvn verify -Ddocker.username=$FDB_DOCKER_USER -Ddocker.password=$FDB_DOCKER_PASS -Dapi.port=4059 -Ddocker.db.image=$DOCKER_DB_IMAGE -B

    - name: Linux / eXist-db 5.0.0
      os: linux
      env:
        - DOCKER_DB_IMAGE=existdb/existdb:5.0.0

    - name: Linux / eXist-db 5.2.0
      os: linux
      env:
        - DOCKER_DB_IMAGE=existdb/existdb:5.2.0

    - name: Linux / eXist-db Latest
      os: linux
      env:
        - DOCKER_DB_IMAGE=existdb/existdb:latest

install: mvn install -Ddocker.skip=true -Dexec.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn verify -Dapi.port=8080 -Ddocker.db.image=$DOCKER_DB_IMAGE -B

cache:
  directories:
    - $HOME/.m2
